
import React, { useState, useEffect } from 'react';
import { HashRouter, Routes, Route, Link, useLocation, useParams, useNavigate } from 'react-router-dom';
import { 
  Github, 
  Linkedin, 
  Mail, 
  MapPin, 
  ExternalLink, 
  GraduationCap, 
  Briefcase, 
  Code, 
  FileText,
  ChevronRight,
  Menu,
  X,
  Database,
  BrainCircuit,
  ArrowLeft,
  Calendar,
  Building2,
  Tag,
  LineChart,
  ListChecks,
  Sparkles,
  Layers,
  CheckCircle2,
  Cpu,
  Calculator,
  Compass,
  RotateCcw,
  Maximize2,
  Info,
  ChevronDown,
  ArrowDown,
  RefreshCw,
  Zap,
  Activity,
  Users,
  Search,
  PenTool,
  ClipboardCheck,
  UserCheck,
  Terminal,
  ShieldCheck,
  MessageSquare
} from 'lucide-react';
import { PROJECTS, EDUCATION, WORK_EXPERIENCE, SKILLS } from './data';
import { Project } from './types';

// Using a professional placeholder that matches the user's profile image
const PROFILE_IMAGE_URL = "https://i.postimg.cc/jdLMNtvk/jie-ping2026-01-28-12-22-25.png";

// --- Diagram Component ---

const ModularPipelineDiagram = () => {
  const steps = [
    {
      title: "Original Model Response",
      description: "Baseline response generated by the LLM",
      color: "bg-indigo-500",
      number: null,
      input: "user_query",
      output: "original response"
    },
    {
      title: "Issue Definition Module",
      description: "Transform vague issues into concrete, well-defined problems",
      color: "bg-indigo-600",
      number: 1,
      input: "knowledge_base, vague issues",
      output: "concrete issues"
    },
    {
      title: "Issue Detection Module",
      description: "Check model's response and assess issue severity",
      color: "bg-rose-500",
      number: 2,
      input: "knowledge_base, original response, concrete issues",
      output: "issues & severity"
    },
    {
      title: "Optimization Suggestion Module",
      description: "Propose optimization suggestions based on identified issues",
      color: "bg-amber-500",
      number: 3,
      input: "knowledge_base, original response, issues & severity",
      output: "suggestions"
    },
    {
      title: "Response Generation Module",
      description: "Generate final optimized response with suggestions",
      color: "bg-emerald-500",
      number: 4,
      input: "knowledge_base, original response, suggestions",
      output: "optimized response"
    }
  ];

  return (
    <div className="flex flex-col items-center my-10 max-w-xl mx-auto p-6 md:p-8 bg-slate-50/50 rounded-[2.5rem] border border-slate-100 animate-in fade-in duration-1000">
      {steps.map((step, index) => (
        <React.Fragment key={index}>
          {/* Module Card */}
          <div className="relative w-full">
            {step.number && (
              <div className="absolute -left-2 -top-2 w-7 h-7 rounded-lg bg-slate-900 text-white flex items-center justify-center font-bold text-xs shadow-lg z-20">
                {step.number}
              </div>
            )}
            <div className="w-full bg-white p-5 rounded-2xl shadow-md border border-slate-100 flex gap-4 transition-transform hover:scale-[1.01] relative z-10">
              <div className={`w-1.5 self-stretch rounded-full ${step.color}`} />
              <div className="flex-1">
                <h4 className="font-bold text-slate-900 text-sm mb-1">{step.title}</h4>
                <p className="text-slate-500 text-[10px] leading-tight mb-3">{step.description}</p>
                
                <div className="grid grid-cols-2 gap-3 pt-2 border-t border-slate-50">
                  <div>
                    <span className="block text-[9px] font-bold text-slate-400 uppercase tracking-wider mb-1">Input</span>
                    <div className="bg-slate-50 px-2 py-1 rounded text-[10px] mono text-slate-600 font-medium">
                      {step.input}
                    </div>
                  </div>
                  <div>
                    <span className="block text-[9px] font-bold text-slate-400 uppercase tracking-wider mb-1">Output</span>
                    <div className="bg-indigo-50 px-2 py-1 rounded text-[10px] mono text-indigo-600 font-bold">
                      {step.output}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Continuous Integrated Arrow Connector */}
          {index < steps.length - 1 && (
            <div className="flex flex-col items-center w-full py-2">
              <div className="h-4 w-px bg-slate-200" />
              <div className="bg-white border border-slate-200 px-4 py-1 rounded-full text-[9px] font-bold text-slate-400 uppercase tracking-widest shadow-sm">
                {step.output}
              </div>
              <div className="h-4 w-px bg-slate-200 relative">
                <div className="absolute -bottom-1 left-1/2 -translate-x-1/2 w-0 h-0 border-l-[4px] border-l-transparent border-r-[4px] border-r-transparent border-t-[6px] border-t-slate-200" />
              </div>
            </div>
          )}
        </React.Fragment>
      ))}

      {/* Final Connector to Success State */}
      <div className="flex flex-col items-center w-full py-2">
        <div className="h-6 w-px bg-slate-200 relative">
           <div className="absolute -bottom-1 left-1/2 -translate-x-1/2 w-0 h-0 border-l-[4px] border-l-transparent border-r-[4px] border-r-transparent border-t-[6px] border-t-slate-200" />
        </div>
      </div>

      {/* Success Badge */}
      <div className="mt-2 bg-emerald-50 border border-emerald-200 text-emerald-700 px-12 py-3 rounded-2xl font-bold text-sm flex items-center gap-3 shadow-sm ring-4 ring-emerald-50 transition-transform hover:scale-105">
        <CheckCircle2 className="w-5 h-5 text-emerald-500" /> Optimized Final Response
      </div>
    </div>
  );
};

// --- GAN Iterative Process Component ---
const GANIterativeProcess = () => {
  const steps = [
    {
      phase: "Round 1",
      title: "Initial Training",
      desc: "Train the generator G(0) on raw simulated images (Rx(0)) and unpaired real clinical data (RY).",
      icon: <Zap className="w-5 h-5 text-amber-500" />
    },
    {
      phase: "Inpainting",
      title: "Structure Refinement",
      desc: "Apply the post-processing inpainting module to generated images, refining vessel continuity and noise patterns into a refined set (R̃x(0)).",
      icon: <Layers className="w-5 h-5 text-indigo-500" />
    },
    {
      phase: "Round 2+",
      title: "Iterative Feedback",
      desc: "Train G(t) using the refined set R̃x(t-1) from the previous round instead of original raw simulated data, progressively bridging the domain gap.",
      icon: <RefreshCw className="w-5 h-5 text-emerald-500" />
    }
  ];

  return (
    <div className="grid grid-cols-1 md:grid-cols-3 gap-6 my-10">
      {steps.map((step, idx) => (
        <div key={idx} className="bg-white p-6 rounded-3xl border border-slate-200 shadow-sm hover:shadow-md transition-shadow relative">
           <div className="absolute top-4 right-4 text-[9px] font-black text-slate-300 uppercase tracking-widest">Step 0{idx+1}</div>
           <div className="w-10 h-10 rounded-2xl bg-slate-50 flex items-center justify-center mb-4">
             {step.icon}
           </div>
           <div className="text-[10px] font-black text-indigo-600 uppercase tracking-widest mb-1">{step.phase}</div>
           <h4 className="font-bold text-slate-900 mb-2">{step.title}</h4>
           <p className="text-xs text-slate-500 leading-relaxed">{step.desc}</p>
        </div>
      ))}
    </div>
  );
};

// --- Tea Simulation Components ---

const TeaDevelopmentFlowchart = () => {
  return (
    <div className="flex flex-col items-center py-10 max-w-2xl mx-auto">
      <div className="w-full bg-white p-8 rounded-[2.5rem] border border-slate-200 shadow-xl overflow-hidden flex flex-col items-center">
        <img 
          src="https://i.postimg.cc/CdpfNxxR/jie-ping2026-02-08-20-50-53.png" 
          alt="Game Development Workflow" 
          className="max-w-full h-auto object-contain"
        />
        <div className="mt-8 grid grid-cols-2 md:grid-cols-4 gap-4 w-full pt-8 border-t border-slate-100">
          <div className="text-center p-3 bg-slate-50 rounded-2xl border border-slate-100">
            <Users className="w-5 h-5 text-indigo-600 mx-auto mb-2" />
            <div className="text-[10px] font-bold text-slate-900 uppercase">Discussion</div>
          </div>
          <div className="text-center p-3 bg-slate-50 rounded-2xl border border-slate-100">
            <PenTool className="w-5 h-5 text-indigo-600 mx-auto mb-2" />
            <div className="text-[10px] font-bold text-slate-900 uppercase">Analysis</div>
          </div>
          <div className="text-center p-3 bg-slate-50 rounded-2xl border border-slate-100">
            <Terminal className="w-5 h-5 text-indigo-600 mx-auto mb-2" />
            <div className="text-[10px] font-bold text-slate-900 uppercase">Dev & Test</div>
          </div>
          <div className="text-center p-3 bg-slate-50 rounded-2xl border border-slate-100">
            <ShieldCheck className="w-5 h-5 text-indigo-600 mx-auto mb-2" />
            <div className="text-[10px] font-bold text-slate-900 uppercase">Review</div>
          </div>
        </div>
      </div>
    </div>
  );
};

const TeaVisualComparison = () => {
  return (
    <div className="space-y-12 my-10">
      {/* Menu Comparison */}
      <div className="space-y-4">
        <div className="flex items-center gap-2 text-indigo-600 font-black text-xs uppercase tracking-widest px-2">
          <Layers className="w-4 h-4" /> Main Menu: From Sketch to Final
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="bg-white p-4 rounded-3xl border border-slate-200 shadow-sm">
            <div className="text-[10px] font-bold text-slate-400 uppercase mb-3 px-2">Initial Concept Sketch</div>
            <img src="https://i.postimg.cc/tgqMXhGK/jie-ping2026-02-08-20-51-54.png" alt="Menu Sketch" className="rounded-2xl w-full h-auto object-cover border border-slate-100" />
          </div>
          <div className="bg-white p-4 rounded-3xl border border-indigo-100 shadow-md ring-1 ring-indigo-50">
            <div className="text-[10px] font-bold text-indigo-600 uppercase mb-3 px-2">Unity Implementation</div>
            <img src="https://i.postimg.cc/fLkqdDLK/jie-ping2026-02-08-20-51-31.png" alt="Menu Final" className="rounded-2xl w-full h-auto object-cover border border-slate-100" />
          </div>
        </div>
      </div>

      {/* Game Interface Comparison */}
      <div className="space-y-4">
        <div className="flex items-center gap-2 text-indigo-600 font-black text-xs uppercase tracking-widest px-2">
          <Activity className="w-4 h-4" /> Gameplay HUD: Layout Evolution
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="bg-white p-4 rounded-3xl border border-slate-200 shadow-sm">
            <div className="text-[10px] font-bold text-slate-400 uppercase mb-3 px-2">Interface Wireframe</div>
            <img src="https://i.postimg.cc/NG3Cyhw3/jie-ping2026-02-08-20-52-02.png" alt="Interface Sketch" className="rounded-2xl w-full h-auto object-cover border border-slate-100" />
          </div>
          <div className="bg-white p-4 rounded-3xl border border-indigo-100 shadow-md ring-1 ring-indigo-50">
            <div className="text-[10px] font-bold text-indigo-600 uppercase mb-3 px-2">Final 3D Rendering</div>
            <img src="https://i.postimg.cc/XY8sDpyS/jie-ping2026-02-08-20-51-19.png" alt="Game Final" className="rounded-2xl w-full h-auto object-cover border border-slate-100" />
          </div>
        </div>
      </div>
    </div>
  );
};

// --- Social Credit Pipeline Diagram ---
const SocialCreditPipelineDiagram = () => {
  const pipeline = [
    {
      title: "Scrapy Crawler",
      description: "Automated downloading of official PDF reports for 130,000+ firms from Credit China.",
      icon: <Layers className="w-5 h-5 text-indigo-500" />
    },
    {
      title: "Raw Data Extraction",
      description: "Parsing semi-structured PDF content into unstructured text blocks and metadata.",
      icon: <Database className="w-5 h-5 text-indigo-500" />
    },
    {
      title: "Information Extraction",
      description: "Cleaning and converting tabular information from reports into structured Excel formats.",
      icon: <ListChecks className="w-5 h-5 text-indigo-500" />
    },
    {
      title: "Panel Data Transformation",
      description: "Final processing to create a clean time-series panel dataset for econometric modeling.",
      icon: <LineChart className="w-5 h-5 text-indigo-500" />
    }
  ];

  return (
    <div className="space-y-4 max-w-2xl mx-auto py-8">
      {pipeline.map((step, idx) => (
        <div key={idx} className="flex flex-col items-center">
          <div className="w-full bg-white p-6 rounded-3xl border border-slate-200 shadow-sm flex items-start gap-5 hover:border-indigo-300 transition-colors">
            <div className="w-12 h-12 rounded-2xl bg-indigo-50 flex items-center justify-center shrink-0">
              {step.icon}
            </div>
            <div>
              <h4 className="font-bold text-slate-900 mb-1">{step.title}</h4>
              <p className="text-sm text-slate-500 leading-relaxed">{step.description}</p>
            </div>
          </div>
          {idx < pipeline.length - 1 && (
            <div className="py-2">
              <ArrowDown className="w-5 h-5 text-slate-300" />
            </div>
          )}
        </div>
      ))}
    </div>
  );
};

// --- EdTech Assessment Specialized Components ---

const ComplexityAnalysis = () => {
  const ccsMetrics = [
    { label: "Loop Depth (D)", weight: "2.0x" },
    { label: "Primitives per Unit (P)", weight: "0.5x" },
    { label: "Unique Parameters (U)", weight: "0.25x" },
    { label: "Total Iterations (T)", weight: "Log Scale" },
    { label: "State Operations (S)", weight: "0.25x" },
    { label: "Curve/Line Variety (C)", weight: "1.0x" },
  ];

  const ccovConcepts = [
    "Move & Turn",
    "Repeat (Loops)",
    "Nested Loops",
    "Arcs",
    "Variables"
  ];

  return (
    <div className="space-y-6">
      <div className="grid lg:grid-cols-2 gap-8 items-stretch">
        {/* Left: CCS */}
        <div className="bg-white p-8 rounded-3xl border border-slate-200 shadow-sm flex flex-col h-full">
          <div className="flex items-center gap-3 mb-8">
            <Cpu className="w-6 h-6 text-indigo-600" />
            <h4 className="text-lg font-bold text-slate-800">Code Complexity Score (CCS)</h4>
          </div>
          <div className="grid grid-cols-1 gap-2.5 flex-grow">
            {ccsMetrics.map((m, i) => (
              <div key={i} className="flex items-center justify-between p-4 bg-slate-50 rounded-2xl border border-slate-100 group hover:border-indigo-200 transition-all duration-200">
                <span className="text-sm font-semibold text-slate-700">{m.label}</span>
                <span className="text-[10px] font-bold bg-indigo-100 text-indigo-700 px-2.5 py-1 rounded-lg shadow-sm">{m.weight}</span>
              </div>
            ))}
          </div>
          <div className="mt-8 pt-6 border-t border-slate-100">
             <div className="text-[10px] font-black text-slate-400 uppercase mb-3 tracking-widest text-center">Formulated Index</div>
             <div className="font-mono text-xs bg-slate-900 text-indigo-300 p-4 rounded-2xl text-center shadow-xl ring-1 ring-white/10">
               CCS = 2D + 0.5P + 0.25U + log₂(T) + 0.25S + C
             </div>
          </div>
        </div>

        {/* Right: CCov */}
        <div className="bg-white p-8 rounded-3xl border border-slate-200 shadow-sm flex flex-col h-full">
          <div className="flex items-center gap-3 mb-8">
            <Layers className="w-6 h-6 text-indigo-600" />
            <h4 className="text-lg font-bold text-slate-800">Content Coverage (CCov)</h4>
          </div>
          <div className="space-y-2.5 flex-grow">
            {ccovConcepts.map((c, i) => (
              <div key={i} className="flex items-center justify-between p-4 bg-slate-50 rounded-2xl border border-slate-100 group hover:bg-emerald-50 transition-all duration-200">
                <span className="text-sm font-semibold text-slate-700">{c}</span>
                <div className="w-7 h-7 rounded-full bg-emerald-100 flex items-center justify-center shadow-inner">
                  <CheckCircle2 className="w-4 h-4 text-emerald-600" />
                </div>
              </div>
            ))}
          </div>
          <div className="mt-8 pt-6 border-t border-slate-100 text-center">
             <div className="text-[10px] font-black text-slate-400 uppercase mb-3 tracking-widest">Weighted Evaluation</div>
             <div className="font-mono text-base font-black text-indigo-600 bg-indigo-50 py-4 rounded-2xl border border-indigo-100 shadow-sm">
               OCS = 0.7 * CCS + 0.3 * (CCov / 5)
             </div>
          </div>
        </div>
      </div>
    </div>
  );
};

const AssessmentFrameworkGrid = () => {
  const bands = [
    { name: "Simple", range: "OCS < 9.0", desc: "Single loop; limited concept use." },
    { name: "Moderate", range: "9.0 ≤ OCS < 14.0", desc: "Clear structure; several primitives." },
    { name: "Complex", range: "14.0 ≤ OCS < 18.0", desc: "Nested loops; rich geometry variety." },
    { name: "Very Complex", range: "OCS ≥ 18.0", desc: "Deep nested structure; mixed lines/arcs." }
  ];

  return (
    <div className="space-y-8">
      <div className="overflow-x-auto rounded-3xl border border-slate-200 bg-white shadow-xl">
        <table className="w-full text-xs border-collapse">
          <thead>
            <tr className="bg-slate-50 border-b border-slate-200">
              <th className="p-4 border-r border-slate-200 text-slate-400 uppercase tracking-widest font-black text-left w-32">Correctness</th>
              <th className="p-4 border-r border-slate-100 font-bold text-slate-700">Low Complexity (Simple)</th>
              <th className="p-4 border-r border-slate-100 font-bold text-slate-700">Moderate Complexity</th>
              <th className="p-4 font-bold text-slate-700">High Complexity (Complex+)</th>
            </tr>
          </thead>
          <tbody>
            <tr className="border-b border-slate-100">
              <td className="p-4 border-r border-slate-200 font-bold text-slate-400 bg-slate-50/30">0 - Incorrect</td>
              <td className="p-4 border-r border-slate-100 text-slate-400 italic">Minimal engagement; random blocks.</td>
              <td className="p-4 border-r border-slate-100 text-slate-400 italic">Confused structure; broken logic.</td>
              <td className="p-4 text-slate-400 italic">Overreaching; chaotic long scripts.</td>
            </tr>
            <tr className="border-b border-slate-100">
              <td className="p-4 border-r border-slate-200 font-bold text-slate-400 bg-slate-50/30">1 - Partial</td>
              <td className="p-4 border-r border-slate-100 text-slate-500">Basic block misuse.</td>
              <td className="p-4 border-r border-slate-100 text-slate-500 italic">Partial reasoning; "guessing" loop counts.</td>
              <td className="p-4 text-slate-500 italic">Complex but shaky; advanced constructs misused.</td>
            </tr>
            <tr className="border-b border-slate-100">
              <td className="p-4 border-r border-slate-200 font-bold text-indigo-600 bg-slate-50/30">2 - Mostly</td>
              <td className="p-4 border-r border-slate-100 text-slate-700 font-medium">Simple & predictable; inefficient.</td>
              <td className="p-4 border-r border-slate-100 text-slate-700 font-medium">Emerging reasoning; visible math logic.</td>
              <td className="p-4 text-slate-700 font-medium italic">High potential; small precision mistakes.</td>
            </tr>
            <tr className="bg-indigo-50/30">
              <td className="p-4 border-r border-slate-200 font-black text-emerald-600 bg-emerald-50/50">3 - Fully</td>
              <td className="p-4 border-r border-slate-100 text-slate-900 font-bold">Safe designs; solid reasoning.</td>
              <td className="p-4 border-r border-slate-100 text-slate-900 font-bold">Confident reasoning; structured scripts.</td>
              <td className="p-4 text-indigo-900 font-black">Expert-like thinking; predicts & optimizes.</td>
            </tr>
          </tbody>
        </table>
      </div>

      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        {bands.map((b, i) => (
          <div key={i} className="p-4 bg-white border border-slate-200 rounded-2xl shadow-sm text-center">
            <div className="text-[10px] font-black text-indigo-600 uppercase mb-1">{b.name} Band</div>
            <div className="text-xs font-bold text-slate-800 mb-1">{b.range}</div>
            <p className="text-[10px] text-slate-500 leading-tight">{b.desc}</p>
          </div>
        ))}
      </div>
    </div>
  );
};

const StudentDesignAnalysis = () => {
  return (
    <div className="space-y-12">
      {/* Case Study Example - Simplified Vertical Layout */}
      <div className="bg-white rounded-[2.5rem] border border-slate-200 overflow-hidden shadow-xl flex flex-col">
        
        {/* Top: Visualizations Side-by-Side */}
        <div className="p-10 bg-slate-50 flex items-center justify-around flex-col md:flex-row gap-12 border-b border-slate-200">
          <div className="relative group flex-1 max-w-sm">
            <div className="absolute -inset-2 bg-indigo-500/10 rounded-3xl blur opacity-0 group-hover:opacity-100 transition-opacity" />
            <div className="relative aspect-square w-full bg-white rounded-3xl shadow-lg flex items-center justify-center p-4 border border-slate-200 overflow-hidden">
              <div className="absolute top-4 left-5 text-[9px] font-black text-slate-400 uppercase tracking-widest z-10 bg-white/80 px-2 py-1 rounded">Design</div>
              <img 
                src="https://i.postimg.cc/QCsHD8tk/jie-ping2026-02-05-13-02-38.png" 
                alt="Student Design Pattern" 
                className="w-full h-full object-contain" 
                />
            </div>
          </div>
          
          <div className="relative group flex-1 max-w-sm">
            <div className="absolute -inset-2 bg-emerald-500/10 rounded-3xl blur opacity-0 group-hover:opacity-100 transition-opacity" />
            <div className="relative aspect-square w-full bg-white rounded-3xl shadow-lg flex items-center justify-center p-4 border border-slate-200 overflow-hidden">
              <div className="absolute top-4 left-5 text-[9px] font-black text-slate-400 uppercase tracking-widest z-10 bg-white/80 px-2 py-1 rounded">Script</div>
              <img 
                src="https://i.postimg.cc/9MDDb8S3/jie-ping2026-02-05-12-50-18.png"
                alt="Student Script Code" 
                className="w-full h-full object-contain"
              />
            </div>
          </div>
        </div>

        {/* Bottom: Only Results and Metrics Grid */}
        <div className="p-12 bg-white">
          <div className="max-w-4xl mx-auto space-y-10">
            {/* Score Cards */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              <div className="p-8 bg-slate-50 rounded-[2rem] border border-slate-100 flex items-center justify-between shadow-sm hover:shadow-md transition-shadow">
                <div>
                  <div className="text-[11px] text-slate-400 font-black uppercase tracking-widest mb-1">OCS Result</div>
                  <div className="text-4xl font-black text-slate-900">8.25</div>
                </div>
              </div>
              <div className="p-8 bg-slate-50 rounded-[2rem] border border-slate-100 flex items-center justify-between shadow-sm hover:shadow-md transition-shadow">
                <div>
                  <div className="text-[11px] text-slate-400 font-black uppercase tracking-widest mb-1">Correctness</div>
                  <div className="text-4xl font-black text-emerald-600">2 / 3</div>
                </div>
              </div>
            </div>

            {/* Metrics Breakdown */}
            <div className="grid grid-cols-3 md:grid-cols-6 gap-4">
              {[
                { l: "D", v: "1", name: "Depth" }, 
                { l: "P", v: "2", name: "Primitives" }, 
                { l: "U", v: "3", name: "Unique" },
                { l: "T", v: "3", name: "Total" }, 
                { l: "S", v: "2", name: "State" }, 
                { l: "C", v: "1", name: "Curves" },
              ].map((stat, i) => (
                <div key={i} className="flex flex-col items-center p-4 bg-white border border-slate-100 rounded-2xl shadow-sm hover:border-indigo-200 hover:bg-indigo-50/10 transition-all">
                  <span className="text-[10px] font-black text-slate-400 uppercase tracking-tighter mb-1">{stat.l}</span>
                  <span className="text-xl font-black text-slate-800 mono">{stat.v}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

// --- Standard UI Components ---

const Navbar = () => {
  const [isOpen, setIsOpen] = useState(false);
  const location = useLocation();

  const links = [
    { name: 'Home', path: '/' },
    { name: 'Projects', path: '/projects' },
    { name: 'Resume', path: '/resume' },
  ];

  return (
    <nav className="sticky top-0 z-50 bg-white/80 backdrop-blur-md border-b border-slate-200">
      <div className="max-w-5xl mx-auto px-6 h-16 flex items-center justify-between">
        <Link to="/" className="text-xl font-bold tracking-tight text-slate-800 flex items-center gap-2">
          <BrainCircuit className="w-6 h-6 text-indigo-600" />
          <span>Xinyue Cheng</span>
        </Link>

        {/* Desktop Links */}
        <div className="hidden md:flex gap-8">
          {links.map((link) => (
            <Link
              key={link.path}
              to={link.path}
              className={`text-sm font-medium transition-colors ${
                location.pathname.startsWith(link.path === '/' ? 'NONE' : link.path) || (link.path === '/' && location.pathname === '/') ? 'text-indigo-600' : 'text-slate-600 hover:text-indigo-500'
              }`}
            >
              {link.name}
            </Link>
          ))}
        </div>

        {/* Mobile Toggle */}
        <button onClick={() => setIsOpen(!isOpen)} className="md:hidden text-slate-600">
          {isOpen ? <X /> : <Menu />}
        </button>
      </div>

      {/* Mobile Menu */}
      {isOpen && (
        <div className="md:hidden bg-white border-b border-slate-200 py-4 px-6 flex flex-col gap-4">
          {links.map((link) => (
            <Link
              key={link.path}
              to={link.path}
              onClick={() => setIsOpen(false)}
              className={`text-sm font-medium ${
                location.pathname === link.path ? 'text-indigo-600' : 'text-slate-600'
              }`}
            >
              {link.name}
            </Link>
          ))}
        </div>
      )}
    </nav>
  );
};

const Footer = () => (
  <footer className="bg-slate-50 border-t border-slate-200 py-12 px-6">
    <div className="max-w-5xl mx-auto flex flex-col md:flex-row justify-between items-center gap-6">
      <div className="text-slate-500 text-sm">
        © {new Date().getFullYear()} Xinyue Cheng. All rights reserved.
      </div>
      <div className="flex gap-6">
        <a href="mailto:chengxy915@gmail.com" className="text-slate-400 hover:text-indigo-600 transition-colors">
          <Mail className="w-5 h-5" />
        </a>
        <a href="https://linkedin.com" target="_blank" rel="noopener noreferrer" className="text-slate-400 hover:text-indigo-600 transition-colors">
          <Linkedin className="w-5 h-5" />
        </a>
        <a href="https://github.com" target="_blank" rel="noopener noreferrer" className="text-slate-400 hover:text-indigo-600 transition-colors">
          <Github className="w-5 h-5" />
        </a>
      </div>
    </div>
  </footer>
);

// --- Pages ---

const HomePage = () => {
  return (
    <div className="animate-in fade-in duration-700">
      <section className="py-20 px-6 max-w-5xl mx-auto">
        <div className="flex flex-col md:flex-row gap-12 items-center">
          <div className="w-48 h-48 md:w-64 md:h-64 rounded-2xl overflow-hidden shadow-xl ring-4 ring-white">
            <img src={PROFILE_IMAGE_URL} alt="Xinyue Cheng" className="w-full h-full object-cover" />
          </div>
          <div className="flex-1 space-y-6 text-center md:text-left">
            <div>
              <h1 className="text-4xl md:text-5xl font-extrabold text-slate-900 tracking-tight mb-2">Xinyue Cheng</h1>
              <p className="text-lg text-indigo-600 font-medium mono">AI & Data-Focused Analyst | Driven by Real-World Impact</p>
            </div>
            
            <p className="text-lg text-slate-600 leading-relaxed max-w-2xl">
              I am a student at Heidelberg University with a strong focus on <span className="text-slate-900 font-semibold">AI and Data-Driven Insights</span>. 
              I enjoy solving complex problems with data, coordinating projects from idea to delivery, and creating business value through smart, user-focused solutions.
            </p>
            
            <div className="flex flex-wrap gap-4 justify-center md:justify-start">
              <Link to="/projects" className="bg-slate-900 text-white px-6 py-3 rounded-lg font-medium hover:bg-slate-800 transition-all flex items-center gap-2">
                View Projects <ChevronRight className="w-4 h-4" />
              </Link>
              <Link to="/resume" className="bg-white border border-slate-200 text-slate-600 px-6 py-3 rounded-lg font-medium hover:border-indigo-400 hover:text-indigo-600 transition-all">
                Read Resume
              </Link>
            </div>

            <div className="flex items-center gap-4 text-slate-500 text-sm justify-center md:justify-start">
               <span className="flex items-center gap-1"><MapPin className="w-4 h-4" /> Heidelberg, Germany</span>
            </div>
          </div>
        </div>
      </section>

      <section className="bg-white py-20 px-6">
        <div className="max-w-5xl mx-auto grid md:grid-cols-2 gap-8">
          <div className="p-8 rounded-xl bg-slate-50 border border-slate-100 hover:shadow-md transition-shadow">
            <LineChart className="w-10 h-10 text-indigo-600 mb-6" />
            <h3 className="text-xl font-bold mb-3 text-slate-900 leading-tight">Data-Driven Impact</h3>
            <p className="text-slate-600 text-sm leading-relaxed">Applying statistical reasoning, Python/SQL, and dashboard tools (like Tableau) to transform raw data into actionable insights. From STEM education impact analysis to ESG modeling, I leverage data to support real-world decisions and business outcomes.</p>
          </div>
          <div className="p-8 rounded-xl bg-slate-50 border border-slate-100 hover:shadow-md transition-shadow">
            <ListChecks className="w-10 h-10 text-indigo-600 mb-6" />
            <h3 className="text-xl font-bold mb-3 text-slate-900 leading-tight">Analytical Project Management</h3>
            <p className="text-slate-600 text-sm leading-relaxed">Led and contributed to multi-phase, cross-functional projects involving Agile workflows, structured testing, sprint planning, and stakeholder reporting — delivering stable software and validated research results on time.</p>
          </div>
          <div className="p-8 rounded-xl bg-slate-50 border border-slate-100 hover:shadow-md transition-shadow">
            <Sparkles className="w-10 h-10 text-indigo-600 mb-6" />
            <h3 className="text-xl font-bold mb-3 text-slate-900 leading-tight">Applied AI & Prompt Engineering</h3>
            <p className="text-slate-600 text-sm leading-relaxed">Worked on optimizing LLM-generated responses through supervised fine-tuning (SFT) and structured prompt design. Designed a multi-step prompting chain that improved response quality and task relevance by 80% compared to the original output.</p>
          </div>
          <div className="p-8 rounded-xl bg-slate-50 border border-slate-100 hover:shadow-md transition-shadow">
            <Layers className="w-10 h-10 text-indigo-600 mb-6" />
            <h3 className="text-xl font-bold mb-3 text-slate-900 leading-tight">End-to-End Data Pipelines</h3>
            <p className="text-slate-600 text-sm leading-relaxed">Built scalable data pipelines with Python, Scrapy, and Pandas to process unstructured and semi-structured inputs. Created structured datasets for time-series modeling, text classification, and longitudinal research use cases.</p>
          </div>
        </div>
      </section>
    </div>
  );
};

const ProjectsPage = () => {
  return (
    <div className="py-16 px-6 max-w-5xl mx-auto animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div className="mb-12">
        <h2 className="text-3xl font-bold text-slate-900 mb-4 text-center md:text-left">Project Portfolio</h2>
        <p className="text-slate-600 max-w-2xl text-center md:text-left">
          A showcase of my research and development work. Click on a project to view the full technical breakdown.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        {PROJECTS.map((project) => (
          <Link 
            key={project.id} 
            to={`/projects/${project.id}`}
            className="group block bg-white rounded-2xl border border-slate-200 overflow-hidden hover:border-indigo-400 hover:shadow-xl transition-all duration-300"
          >
            <div className="p-8 h-full flex flex-col">
              <div className="flex justify-between items-start mb-4">
                <h3 className="text-xl font-bold text-slate-900 group-hover:text-indigo-600 transition-colors">
                  {project.title}
                </h3>
                <ChevronRight className="w-5 h-5 text-slate-300 group-hover:text-indigo-500 transition-colors" />
              </div>
              <p className="text-slate-600 text-sm mb-6 flex-grow leading-relaxed">
                {project.summary}
              </p>
              <div className="flex flex-wrap gap-2 mt-auto">
                {project.techStack.slice(0, 3).map(tech => (
                  <span key={tech} className="px-2 py-1 bg-slate-50 text-slate-500 text-[10px] uppercase tracking-wider rounded font-semibold border border-slate-100">
                    {tech}
                  </span>
                ))}
                {project.techStack.length > 3 && (
                  <span className="px-2 py-1 text-slate-400 text-[10px] uppercase font-semibold">
                    +{project.techStack.length - 3} more
                  </span>
                )}
              </div>
            </div>
          </Link>
        ))}
      </div>
    </div>
  );
};

const ProjectDetailPage = () => {
  const { projectId } = useParams();
  const navigate = useNavigate();
  const project = PROJECTS.find(p => p.id === projectId);

  useEffect(() => {
    window.scrollTo(0, 0);
  }, [projectId]);

  if (!project) {
    return (
      <div className="py-32 text-center">
        <h2 className="text-2xl font-bold text-slate-800">Project Not Found</h2>
        <Link to="/projects" className="text-indigo-600 hover:underline mt-4 inline-block">Back to Projects</Link>
      </div>
    );
  }

  return (
    <div className="animate-in fade-in duration-500">
      <div className="bg-slate-900 text-white py-20 px-6">
        <div className="max-w-4xl mx-auto">
          <button 
            onClick={() => navigate(-1)}
            className="flex items-center gap-2 text-slate-400 hover:text-white transition-colors mb-8 group"
          >
            <ArrowLeft className="w-4 h-4 group-hover:-translate-x-1 transition-transform" /> Back
          </button>
          <div className="space-y-4">
            <h1 className="text-3xl md:text-5xl font-extrabold tracking-tight leading-tight">{project.title}</h1>
            <div className="flex flex-wrap items-center gap-6 text-slate-400 text-sm">
              <span className="flex items-center gap-2"><Calendar className="w-4 h-4" /> {project.period}</span>
              <span className="flex items-center gap-2"><Building2 className="w-4 h-4" /> {project.institution}</span>
              <span className="flex items-center gap-2"><Briefcase className="w-4 h-4" /> {project.role}</span>
            </div>
          </div>
        </div>
      </div>

      <div className="max-w-4xl mx-auto py-16 px-6 grid md:grid-cols-3 gap-12">
        <div className="md:col-span-2 space-y-12">
          <section>
            <h2 className="text-2xl font-bold text-slate-900 mb-4">Background & Context</h2>
            <p className="text-slate-700 leading-relaxed text-lg">
              {project.background}
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 mb-4">Technical Approach</h2>
            <div className="bg-slate-50 p-8 rounded-2xl border border-slate-100">
              <p className="text-slate-700 leading-relaxed italic">
                {project.methodology}
              </p>
            </div>
          </section>

          {/* Conditional technical documentation sections for EdTech Project */}
          {project.id === "edtech-stem-africa" && (
            <div className="space-y-20 py-12 border-y border-slate-100">
              <section id="assessment-metrics">
                <div className="mb-10">
                  <h2 className="text-3xl font-black text-slate-900 mb-2">Complexity & Coverage Metrics</h2>
                  <p className="text-slate-500 text-sm italic">Formal assessment of structural complexity (CCS) and pedagogical alignment (CCov).</p>
                </div>
                <ComplexityAnalysis />
              </section>

              <section id="rubric-matrix">
                <div className="mb-10">
                  <h2 className="text-3xl font-black text-slate-900 mb-2">Evaluation Matrix</h2>
                  <p className="text-slate-500 text-sm italic">Integrating correctness with design complexity to determine student proficiency bands.</p>
                </div>
                <AssessmentFrameworkGrid />
              </section>

              <section id="student-analysis">
                <div className="mb-10">
                  <h2 className="text-3xl font-black text-slate-900 mb-2">Case Study Analysis</h2>
                  <p className="text-slate-500 text-sm italic">Example student artifact evaluation using design patterns and script logic.</p>
                </div>
                <StudentDesignAnalysis />
              </section>
            </div>
          )}

          {/* Conditional technical documentation sections for Social Credit Project */}
          {project.id === "social-credit-impact" && (
            <div className="space-y-20 py-12 border-y border-slate-100">
              <section id="pdf-showcase">
                <div className="mb-10">
                  <h2 className="text-3xl font-black text-slate-900 mb-2">Source Data: Credit Reports</h2>
                  <p className="text-slate-500 text-sm italic">Visual breakdown of semi-structured PDF reports from 'Credit China' used for extraction.</p>
                </div>
                <div className="flex flex-col gap-8">
                  <div className="bg-white p-6 rounded-3xl border border-slate-200 shadow-sm flex flex-col">
                    <div className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-4">Report Summary Page</div>
                    <img src="https://i.postimg.cc/yxTx9ZQR/jie-ping2026-02-05-13-07-22.png" alt="PDF Summary Page" className="rounded-xl border border-slate-100 w-full h-auto object-cover shadow-inner" />
                  </div>
                  <div className="bg-white p-6 rounded-3xl border border-slate-200 shadow-sm flex flex-col">
                    <div className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-4">Detailed License Info</div>
                    <img src="https://i.postimg.cc/VLD5kX0M/jie-ping2026-02-05-13-07-39.png" alt="PDF Detail Page" className="rounded-xl border border-slate-100 w-full h-auto object-cover shadow-inner" />
                  </div>
                </div>
              </section>

              <section id="data-pipeline">
                <div className="mb-10">
                  <h2 className="text-3xl font-black text-slate-900 mb-2">Data Processing Pipeline</h2>
                  <p className="text-slate-500 text-sm italic">Automated workflow for extracting longitudinal datasets from over 130,000 corporate records.</p>
                </div>
                <SocialCreditPipelineDiagram />
              </section>
            </div>
          )}

          {/* Conditional technical documentation sections for GAN Project */}
          {project.id === "gan-angiograms" && (
            <div className="space-y-20 py-12 border-y border-slate-100">
              <section id="gan-architecture">
                <div className="mb-10">
                  <h2 className="text-3xl font-black text-slate-900 mb-2">Model Architecture</h2>
                  <p className="text-slate-500 text-sm italic">An overview of the VAttentionGAN generator integrated with an adaptive loss schedule and inpainting module for iterative structure refinement.</p>
                </div>
                <div className="bg-white p-8 rounded-[2.5rem] border border-slate-200 shadow-xl overflow-hidden">
                  <img 
                    src="https://i.postimg.cc/52GfG3D2/jie-ping2026-02-05-21-31-01.png" 
                    alt="GAN Architecture Diagram" 
                    className="w-full h-auto object-contain"
                  />
                  <div className="mt-8 grid grid-cols-1 md:grid-cols-2 gap-8 pt-8 border-t border-slate-100">
                    <div className="space-y-3">
                      <div className="flex items-center gap-2 text-indigo-600 font-bold text-xs uppercase tracking-widest">
                        <Activity className="w-4 h-4" /> Key Components
                      </div>
                      <ul className="text-xs text-slate-600 space-y-2 list-disc pl-4 leading-relaxed">
                        <li><strong>VAttentionGAN Generator:</strong> Focuses on vessel-specific features using specialized attention blocks.</li>
                        <li><strong>Inpainting Module:</strong> Post-processes the output to handle structural discontinuities and noise artifacts.</li>
                        <li><strong>Adaptive Loss Schedule:</strong> Dynamically weights different loss components (adversarial, perceptual, structure) during training.</li>
                      </ul>
                    </div>
                    <div className="space-y-3">
                      <div className="flex items-center gap-2 text-emerald-600 font-bold text-xs uppercase tracking-widest">
                        <RefreshCw className="w-4 h-4" /> Refinement Loop
                      </div>
                      <p className="text-xs text-slate-600 leading-relaxed italic">
                        The refined set is fed back into the training loop, allowing the generator to progressively learn the complex domain mapping between simulation and real clinical noise patterns.
                      </p>
                    </div>
                  </div>
                </div>
              </section>

            </div>
          )}

          {/* Conditional technical documentation sections for Tea Game Project */}
          {project.id === "tea-simulation" && (
            <div className="space-y-20 py-12 border-y border-slate-100">
              <section id="dev-lifecycle">
                <div className="mb-10">
                  <h2 className="text-3xl font-black text-slate-900 mb-2">Development Lifecycle</h2>
                  <p className="text-slate-500 text-sm italic">Our team's rigorous workflow for task management, testing, and continuous code improvement.</p>
                </div>
                <TeaDevelopmentFlowchart />
              </section>

              <section id="concept-vs-reality">
                <div className="mb-10">
                  <h2 className="text-3xl font-black text-slate-900 mb-2">Concept vs. Reality</h2>
                  <p className="text-slate-500 text-sm italic">Bridging hand-drawn interface concepts with final Unity 3D implementations.</p>
                </div>
                <TeaVisualComparison />
              </section>
            </div>
          )}

          <section>
            <h2 className="text-2xl font-bold text-slate-900 mb-4">My Core Contributions</h2>
            <ul className="space-y-4">
              {project.contributions.map((item, i) => (
                <li key={i} className="flex gap-4">
                  <div className="flex-shrink-0 w-6 h-6 rounded-full bg-indigo-100 text-indigo-600 flex items-center justify-center text-xs font-bold">{i+1}</div>
                  <span className="text-slate-700 leading-relaxed">{item}</span>
                </li>
              ))}
            </ul>
          </section>

          <section>
             <h2 className="text-2xl font-bold text-slate-900 mb-4">Results & Impact</h2>
             <div className="grid grid-cols-1 gap-4 mb-12">
                {project.results.map((res, i) => (
                  <div key={i} className="p-4 bg-white border border-slate-200 rounded-lg flex items-center gap-3">
                    <div className="w-2 h-2 rounded-full bg-green-500" />
                    <span className="text-slate-800 font-medium">{res}</span>
                  </div>
                ))}
             </div>

             {/* LLM Workflow Diagram */}
             {project.id === "llm-performance-sft" && (
                <div className="border-t border-slate-100 pt-12 animate-in fade-in slide-in-from-top-4 duration-1000">
                  <h2 className="text-2xl font-bold text-slate-900 mb-4">Project: LLM Response Optimizer</h2>
                  <p className="text-slate-600 text-sm mb-6 leading-relaxed">
                    The visualization below illustrates the end-to-end modular workflow designed to transform raw outputs from large language models into high-quality, fine-tuned results. This is achieved through iterative modules for issue detection and optimization. 
                  </p>
                  <p className="text-slate-600 text-sm mb-6 leading-relaxed">
                    The project focuses on student article text, with a knowledge_base component that stores both general writing standards and genre-specific guidelines. Each module corresponds to a structured prompt, with inputs and outputs represented in JSON format. The entire pipeline is implemented in Python, and each output is generated via calls to a large language model API.
                  </p>
                  <ModularPipelineDiagram />
                </div>
             )}
          </section>
        </div>

        <aside className="md:col-span-1 space-y-8">
          <div className="sticky top-24 space-y-8">
            <div className="p-6 bg-white border border-slate-200 rounded-2xl shadow-sm">
              <h3 className="text-sm font-bold text-slate-400 uppercase tracking-widest mb-4 flex items-center gap-2">
                <Tag className="w-4 h-4" /> Tech Stack
              </h3>
              <div className="flex flex-wrap gap-2">
                {project.techStack.map(tech => (
                  <span key={tech} className="px-3 py-1 bg-slate-50 text-slate-600 text-xs font-bold rounded-lg border border-slate-100 uppercase tracking-wide">
                    {tech}
                  </span>
                ))}
              </div>
            </div>
          </div>
        </aside>
      </div>
    </div>
  );
};

const ResumePage = () => {
  const getProjectForWork = (company: string) => {
    if (company.includes('ByteDance')) return PROJECTS.find(p => p.id === 'llm-performance-sft');
    if (company.includes('African Institute')) return PROJECTS.find(p => p.id === 'edtech-stem-africa');
    if (company.includes('Leibniz Centre')) return PROJECTS.find(p => p.id === 'social-credit-impact');
    return null;
  };

  return (
    <div className="py-16 px-6 max-w-5xl mx-auto animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-12 gap-8">
        <div className="flex-1">
          <h2 className="text-3xl font-bold text-slate-900">Curriculum Vitae</h2>
          <p className="text-slate-600">Xinyue Cheng · Professional Profile</p>
          <div className="flex gap-4 mt-4">
             <button className="flex items-center gap-2 bg-slate-900 text-white px-4 py-2 rounded-lg hover:bg-slate-800 transition-all text-sm font-medium">
               <FileText className="w-4 h-4" /> Download PDF
             </button>
             <a href="mailto:chengxy915@gmail.com" className="p-2 border border-slate-200 rounded-lg hover:bg-slate-50 text-slate-600 transition-colors">
               <Mail className="w-5 h-5" />
             </a>
          </div>
        </div>
        <div className="w-24 h-24 md:w-32 md:h-32 rounded-xl overflow-hidden shadow-lg border-2 border-white flex-shrink-0">
          <img src={PROFILE_IMAGE_URL} alt="Xinyue Cheng" className="w-full h-full object-cover" />
        </div>
      </div>

      <div className="space-y-16">
        {/* Education */}
        <section>
          <div className="flex items-center gap-2 mb-8 border-b border-slate-200 pb-2">
            <GraduationCap className="w-5 h-5 text-indigo-600" />
            <h3 className="text-xl font-bold uppercase tracking-tight text-slate-800">Education</h3>
          </div>
          <div className="space-y-8">
            {EDUCATION.map((edu, i) => (
              <div key={i} className="flex flex-col md:flex-row md:justify-between items-start gap-1">
                <div>
                  <h4 className="font-bold text-slate-900 text-lg leading-tight">{edu.degree}</h4>
                  <p className="text-slate-600">{edu.institution}</p>
                  {edu.details?.map((d, idx) => (
                    <p key={idx} className="text-sm text-indigo-600 font-semibold mt-1 inline-block bg-indigo-50 px-2 py-0.5 rounded">{d}</p>
                  ))}
                </div>
                <div className="text-sm text-slate-500 font-medium md:text-right mt-1">{edu.period}</div>
              </div>
            ))}
          </div>
        </section>

        {/* Work Experience */}
        <section>
          <div className="flex items-center gap-2 mb-8 border-b border-slate-200 pb-2">
            <Briefcase className="w-5 h-5 text-indigo-600" />
            <h3 className="text-xl font-bold uppercase tracking-tight text-slate-800">Work Experience</h3>
          </div>
          <div className="space-y-12">
            {WORK_EXPERIENCE.map((exp, i) => {
              const linkedProject = getProjectForWork(exp.company);
              return (
                <div key={i}>
                  <div className="flex flex-col md:flex-row md:justify-between items-start mb-4 gap-1">
                    <div>
                      {linkedProject ? (
                        <Link 
                          to={`/projects/${linkedProject.id}`}
                          className="group inline-flex items-center gap-2 font-bold text-slate-900 text-xl hover:text-indigo-600 transition-colors"
                        >
                          {exp.role} 
                          <ExternalLink className="w-4 h-4 opacity-0 group-hover:opacity-100 transition-opacity" />
                        </Link>
                      ) : (
                        <h4 className="font-bold text-slate-900 text-xl">{exp.role}</h4>
                      )}
                      <p className="text-indigo-600 font-semibold flex items-center gap-2">
                        {exp.company} <span className="text-slate-300 font-normal">|</span> <span className="text-slate-500 font-medium text-sm">{exp.location}</span>
                      </p>
                    </div>
                    <div className="text-sm text-slate-500 font-bold md:text-right">{exp.period}</div>
                  </div>
                  <div className="mb-4">
                    <p className="text-slate-700 leading-relaxed font-medium mb-2">{exp.scope}</p>
                  </div>
                  <ul className="space-y-2">
                    {exp.responsibilities.map((res, idx) => (
                      <li key={idx} className="flex gap-3 text-slate-600 text-sm">
                        <div className="w-1.5 h-1.5 rounded-full bg-slate-300 mt-1.5 flex-shrink-0" />
                        <span className="leading-relaxed">{res}</span>
                      </li>
                    ))}
                  </ul>
                  {linkedProject && (
                    <div className="flex flex-wrap gap-2 mt-4">
                      {linkedProject.techStack.map(tech => (
                        <span key={tech} className="px-2 py-0.5 bg-slate-100 text-slate-500 text-[10px] font-bold uppercase rounded border border-slate-200">
                          {tech}
                        </span>
                      ))}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </section>

        {/* Project Experience (Last two projects) */}
        <section>
          <div className="flex items-center gap-2 mb-8 border-b border-slate-200 pb-2">
            <Code className="w-5 h-5 text-indigo-600" />
            <h3 className="text-xl font-bold uppercase tracking-tight text-slate-800">Project Experience</h3>
          </div>
          <div className="space-y-12">
            {PROJECTS.slice(-2).map((project, i) => (
              <div key={i}>
                <div className="flex flex-col md:flex-row md:justify-between items-start mb-4 gap-1">
                  <div>
                    <Link 
                      to={`/projects/${project.id}`} 
                      className="group inline-flex items-center gap-2 font-bold text-slate-900 text-xl hover:text-indigo-600 transition-colors"
                    >
                      {project.title} 
                      <ExternalLink className="w-4 h-4 opacity-0 group-hover:opacity-100 transition-opacity" />
                    </Link>
                    <p className="text-indigo-600 font-semibold flex items-center gap-2">
                      {project.role} <span className="text-slate-300 font-normal">|</span> <span className="text-slate-500 font-medium text-sm">{project.institution}</span>
                    </p>
                  </div>
                  <div className="text-sm text-slate-500 font-bold md:text-right">{project.period}</div>
                </div>
                <div className="mb-4">
                  <p className="text-slate-700 leading-relaxed font-medium mb-2">{project.summary}</p>
                </div>
                <ul className="space-y-2 mb-4">
                  {project.contributions.slice(0, 2).map((item, idx) => (
                    <li key={idx} className="flex gap-3 text-slate-600 text-sm">
                      <div className="w-1.5 h-1.5 rounded-full bg-slate-300 mt-1.5 flex-shrink-0" />
                      <span className="leading-relaxed">{item}</span>
                    </li>
                  ))}
                </ul>
                <div className="flex flex-wrap gap-2">
                  {project.techStack.map(tech => (
                    <span key={tech} className="px-2 py-0.5 bg-slate-100 text-slate-500 text-[10px] font-bold uppercase rounded border border-slate-200">
                      {tech}
                    </span>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* Skills */}
        <section>
          <div className="flex items-center gap-2 mb-8 border-b border-slate-200 pb-2">
            <Tag className="w-5 h-5 text-indigo-600" />
            <h3 className="text-xl font-bold uppercase tracking-tight text-slate-800">Technical Skills</h3>
          </div>
          <div className="grid md:grid-cols-3 gap-8">
            {SKILLS.map((group, i) => (
              <div key={i} className="space-y-4">
                <h4 className="text-xs font-bold uppercase tracking-widest text-slate-400 border-l-2 border-indigo-200 pl-3">{group.category}</h4>
                <div className="flex flex-wrap gap-2">
                  {group.skills.map((skill, idx) => (
                    <span key={idx} className="px-3 py-1 bg-white border border-slate-200 rounded text-sm text-slate-700 font-medium hover:border-indigo-200 transition-colors">
                      {skill}
                    </span>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </section>
      </div>
    </div>
  );
};

const App = () => {
  return (
    <HashRouter>
      <div className="min-h-screen flex flex-col selection:bg-indigo-100 selection:text-indigo-900">
        <Navbar />
        <main className="flex-grow">
          <Routes>
            <Route path="/" element={<HomePage />} />
            <Route path="/projects" element={<ProjectsPage />} />
            <Route path="/projects/:projectId" element={<ProjectDetailPage />} />
            <Route path="/resume" element={<ResumePage />} />
          </Routes>
        </main>
        <Footer />
      </div>
    </HashRouter>
  );
};

export default App;
